### ISSUE TITLE
Issue Paging with Search Criteria

### ISSUE THREAD

**Issue by BlueRubberDuck13** [LazZiya/TagHelpers#12]
Hi

When trying to page with search criteria in, it fails by putting the entire search string in the search box and therefore not being able to find anything. e.g. EnglishCT=AllCulturesS=10

Using the sample project

1) Enter Search value e.g. "English"
2) Click Search Button
3) Table is Filtered Correctly
4) Click a page button
5) Table is Empty
     Search Value is "EnglishCT=AllCulturesS=10" (And is contained in the Search Input box)

This is in Core 3.1 if that matters (Sorry new to this programming game)

RD

**Comment by LazZiya** [comment]
Hi @BlueRubberDuck13 

Thanks for reporting the issue, it is happenning excactly on the second paging click due to missing the **&** between the search query and paging parameters!

I will fix it soon...

**Comment by LazZiya** [comment]
issue fixed with new release v4.0.1 and published to nuget as well,

Thanks again @BlueRubberDuck13 :)

**Comment by BlueRubberDuck13** [comment]
Amazing,  

That's really great, and works perfectly now

Many Thanks
