### ISSUE TITLE
Customize badges size

### ISSUE THREAD

**Issue by pazunino** [LazZiya/TagHelpers#17]
When there are too many pages and rows it would be good to warn the user with a more noticeable badge, to prevent for example a export of too many rows. 

I like that you can put a style Hx to the badges to increase the size. I achieved this enclosing paging tag with a styled H3 span but caused severe side effects on the whole paging control.

Good job.
Regards.
Pedro.

**Comment by LazZiya** [comment]
Hi @pazunino ,

I tried to reproduce your issue, and I used bootstraps `display-4` to enlarge the badge size with some additional styling as below:

````html
<paging page-no="Model.P"
        page-size="Model.S"
        total-records="Model.TotalRecords"
        class-page-size-div="col-2"
        class-info-div="col-3"
        text-total-pages="P"
        text-total-records="R"
        class-total-pages="display-4 text-danger text-center font-weight-bold bg-warning rounded d-block m-1"
        class-total-records="display-4 text-dark text-center font-weight-bold bg-secondary rounded d-block m-1">
</paging>
```` 

And the result was not bad :)
![image](https://user-images.githubusercontent.com/22244584/118278911-30842d80-b4d3-11eb-9ba3-169864ea2330.png)

Can you share your code and result? maybe I can help to improve it.

**Comment by pazunino** [comment]
Hi @LazZiya,
Sorry, viewing your sample it is more clear now.
I only tried with H6 class but there are many other possibilities.
Thank you for your answer and your time.
Excellent job.
Regards
Pedro.

**Comment by LazZiya** [comment]
glad to help :)
