### ISSUE TITLE
Deployment to prodution server

### ISSUE THREAD

**Issue by saraivaaugusto** [LazZiya/TagHelpers#30]
**Describe the bug**
When I deploy the app (.NET 7) to the production server the page numbers doesn't work. In development all work fine.

**To Reproduce**
1. Click on page number it stay with focus but nothing happens.

**Expected behavior**
View the next/before records after click on page number.

**Screenshots**
![image](https://user-images.githubusercontent.com/109981990/209575243-de34d940-2e96-4a58-b5f4-34e0a746d791.png).

**Desktop (please complete the following information):**
 - OS: [Windows Server 2019 Standard]
 - Browser All

**Comment by LazZiya** [comment]
If you are using BS5 just add render mode setting:

````html
<paging render-mode="Bootstrap5">
</paging>
````

also #26, #27 and [styling attributes](https://docs.ziyad.info/en/LazZiya.TagHelpers/v6.0/Paging-TagHelper-Attributes.md#styling-attributes) could help,

**Comment by saraivaaugusto** [comment]
Hello,

I already have this option.

<paging class="pagination text-end" total-records="@Model.TotalRecords" page-size="@Model.S" page-no="@Model.P"
        render-mode="Bootstrap5" ajax="true" ajax-update="#card-sales" ajax-url="?handler=CardSalesPartial">
</paging>

**Comment by saraivaaugusto** [comment]
<paging class="pagination text-end" total-records="@Model.TotalRecords" page-size="@Model.S" page-no="@Model.P"
        render-mode="Bootstrap5" ajax="true" ajax-update="#card-sales" ajax-url="?handler=CardSalesPartial">
</paging>

**Comment by saraivaaugusto** [comment]
![image](https://user-images.githubusercontent.com/109981990/209837469-f712bf44-9bb2-46b1-a00a-232741476c8c.png)

**Comment by LazZiya** [comment]
Do you see any errors in the console?

**Comment by saraivaaugusto** [comment]
Hi,

 

Yes, I have,
