### ISSUE TITLE
Thousands separator in Total Records

### ISSUE THREAD

**Issue by pazunino** [LazZiya/TagHelpers#35]
Hi, great job.
Despite the web app localization the Total Records number always shows a comma as a thousands separator.
I need to configure to use a dot.
Thanks

**Comment by LazZiya** [comment]
Hi, thanks.

I did some tests and everything worked fine, the thousands separator is changing depending on the current culture in the app.

Can you check your localization setup and selected culture settings?

**Comment by pazunino** [comment]
Fixed now, 
It works.
Thanks.
