### ISSUE TITLE
appsetting not working

### ISSUE THREAD

**Issue by hamed8080** [LazZiya/TagHelpers#7]
hello i put setting in json file appsettings.json but not affect!
using .net core 3 and 3.1.0 lazziya

**Comment by LazZiya** [comment]
Thanks for reporting this issue, just confirmed json settings is not working properly! I will try to publish a fix asap...

**Comment by hamed8080** [comment]
Thanks for amazing library. This saved my time a lot .

**Comment by LazZiya** [comment]
- Fixed with e18be12
- Install [nuget package to v3.1.1](https://www.nuget.org/packages/LazZiya.TagHelpers/3.1.1) or newer for fixing the issue.
