### ISSUE TITLE
Query string resets when items per page is changed

### ISSUE THREAD

**Issue by devWaleed** [LazZiya/TagHelpers#8]
**Describe the bug**
Query string resets when items per page is changed.

**To Reproduce**
We have a form which posts to the same page and based on that form we show pagination. Now if I change items per page amount from 10 to 20, it goes to myurl.com/Stock?s=20. It resets all other parameters which were included in form. 

We have this for items per page:

`<form class="form-inline" method="get"><div class="form-group"><label for="pageSizeControl">Items per page&nbsp;</label><select class="form-control" name="s" onchange="this.form.submit();"><option>10</option><option>20</option><option selected="selected">30</option></select></div></form>`

This form is submitted onChange. Clearly ignoring QS parameters. Is there any option to add QS here somehow please?

**Comment by devWaleed** [comment]
I used the following script: https://www.raymondcamden.com/2013/12/11/Quick-Sample-Appending-URL-data-to-a-Form-post-with-JavaScript

This adds QS as hidden fields right before form is posted. You can use this as well or do server side hidden form fields as well.

**Comment by LazZiya** [comment]
Thanks for reporting this issue, I'll provide a built-in solution to include the query string value when page size is changed.

**Comment by LazZiya** [comment]
@devWaleed , issue fixed with 67a6436
Also published to nuget [v3.1.2](https://www.nuget.org/packages/LazZiya.TagHelpers/3.1.2)

hope this will help have a cleaner code without additional scripts :)
