### ISSUE TITLE
How do you change number of items per page in Pagination

### ISSUE THREAD

**Issue by devWaleed** [LazZiya/TagHelpers#9]
How do you change items per page dropdown values? I want to show 15, 30 and 60 in dropdown.

**Comment by LazZiya** [comment]
Use the builtin properties as below:
````html
<paging total-records="Model.TotalRecords"
            page-no="Model.PageNo"
            page-size="Model.PageSize"
            page-size-nav-block-size="15" <!-- min page size -->
            page-size-nav-max-items="5"> <!-- how many items to show in the dropdown -->
    </paging>
````

See [page size](http://demo.ziyad.info/en/Paging#page-size) in the demo page for more details .

**Comment by devWaleed** [comment]
@LazZiya Hey, is it possible to show only 15 and 25 some how? block-size option only takes int as input not array or string.

**Comment by LazZiya** [comment]
Hi @devWaleed, currently it is using a formula to multiply block size by max items, so it can be 15 and 30 as below: 

````cs
<paging total-records="Model.TotalRecords"
    page-no="Model.PageNo"
    page-size="Model.PageSize"
    page-size-nav-block-size="15"
    page-size-nav-max-items="2">
</paging>
````

but I'll consider adding int array as a string in the next version e.g. "15-25-40"
